steps:
  # Backend Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gfip-backend', './backend']
  # Frontend Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gfip-frontend', './frontend']
  
  # Push Images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gfip-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gfip-frontend']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'gfip-backend', '--image', 'gcr.io/$PROJECT_ID/gfip-backend', '--region', 'us-central1', '--allow-unauthenticated']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'gfip-frontend', '--image', 'gcr.io/$PROJECT_ID/gfip-frontend', '--region', 'us-central1', '--allow-unauthenticated']
